### ISSUE TITLE
Rename symbol offers the whole function signature, not a symbol

### ISSUE THREAD

**Issue by timsneath** [swiftlang/sourcekit-lsp#1604]
**Describe the bug**
Given the below function signature:
![image](https://github.com/user-attachments/assets/52557198-ba25-4cd0-a79f-b42c2de081b0)

I should be able to rename just one of the parameters with the Rename Symbol command, and have the change propogate throughout the system. Instead, I get prompted to rename the entire function. This is contrary to how other languages work in VSCode, where the rename symbol command is focused on a single symbol.

I'd instead expect to be able to just rename "message", without making changes inline to the full function signature.

**Environment**
 - OS: [e.g. Ubuntu 20.04]: 15.0 Beta (24A5298h)
 - Swift version (output of `swift --version`): swift-driver version: 1.112.3 Apple Swift version 6.0 (swiftlang-6.0.0.6.8 clang-1600.0.23.1)
 - Visual Studio Code version: Version: 1.91.1 (Universal)
 - vscode-swift version: v1.10.6

**Comment by adam-fowler** [comment]
I actually quite like the full function name, as it does define the function signature, but I can see how this might be annoying with functions that have many parameters.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://132977406

**Comment by ahoppen** [comment]
The behavior of showing the entire function signature was intentional. It signifies that you are doing a rename of the parameter label, which affects callers, instead of just the internal parameter name within the function body. It also gives the option to rename multiple argument labels at once. 

We can re-consider this if a consensus in the community is reached that only showing only the parameter’s name would be better than showing the entire signature. But seems like for now opinions are split.
